"""Discord client and bounded, isolated conversation state."""

from __future__ import annotations

import asyncio
import io
import time
from collections import OrderedDict
from dataclasses import dataclass, field
from typing import Dict, Optional

import discord
from discord import app_commands

from src import personas
from src.config import BotConfig
from src.providers import ProviderError, ProviderManager, ProviderType


@dataclass(frozen=True)
class ConversationKey:
    guild_id: int
    channel_id: int
    user_id: int
    private: bool


@dataclass
class Conversation:
    messages: list[dict[str, str]] = field(default_factory=list)
    last_used: float = field(default_factory=time.monotonic)
    in_flight: bool = False


@dataclass
class UserChannelSettings:
    provider: ProviderType
    model: str
    persona: str = "standard"
    private: bool = True
    last_used: float = field(default_factory=time.monotonic)


class BotRequestError(RuntimeError):
    """Safe, user-facing request rejection generated by the bot itself."""


class DiscordClient(discord.Client):
    def __init__(self, config: BotConfig, provider_manager=None) -> None:
        intents = discord.Intents.default()
        intents.message_content = config.enable_message_content
        super().__init__(intents=intents)
        self.tree = app_commands.CommandTree(self)
        self.config = config
        self.provider_manager = provider_manager or ProviderManager()
        self.conversations: OrderedDict[ConversationKey, Conversation] = OrderedDict()
        self.settings: Dict[tuple[int, int, int], UserChannelSettings] = {}
        self.cooldowns: Dict[tuple[int, int, int], float] = {}
        self.replyall_enabled: set[int] = set()
        self._capacity = asyncio.Semaphore(config.max_concurrent_requests)
        self._registered = False

    async def setup_hook(self) -> None:
        if self._registered:
            return
        self._register_commands()
        await self.tree.sync()
        self._registered = True

    async def close(self) -> None:
        close = getattr(self.provider_manager, "close", None)
        if close:
            result = close()
            if asyncio.iscoroutine(result):
                await result
        await super().close()

    def _scope(self, interaction_or_message) -> tuple[int, int, int]:
        guild = getattr(interaction_or_message, "guild", None)
        channel = getattr(interaction_or_message, "channel", None)
        user = getattr(interaction_or_message, "user", None) or getattr(
            interaction_or_message, "author", None
        )
        if user is None:
            raise BotRequestError("Unable to identify the Discord user for this request.")
        return (getattr(guild, "id", 0), getattr(channel, "id", 0), user.id)

    def get_settings(self, scope: tuple[int, int, int]) -> UserChannelSettings:
        self._prune()
        if scope not in self.settings:
            if len(self.settings) >= self.config.max_sessions:
                raise BotRequestError("The bot is at its session limit; try again later.")
            self.settings[scope] = UserChannelSettings(
                ProviderType(self.config.default_provider), self.config.default_model, private=True
            )
        value = self.settings[scope]
        value.last_used = time.monotonic()
        return value

    def allowed(self, scope: tuple[int, int, int]) -> bool:
        guild_id, channel_id, _ = scope
        return (
            not self.config.allowed_guild_ids or guild_id in self.config.allowed_guild_ids
        ) and (not self.config.allowed_channel_ids or channel_id in self.config.allowed_channel_ids)

    def is_admin(self, user_id: int, interaction=None) -> bool:
        if user_id in self.config.bot_admin_ids:
            return True
        perms = getattr(interaction, "permissions", None)
        return bool(perms and getattr(perms, "manage_channels", False))

    def _prune(self, now: Optional[float] = None) -> None:
        now = time.monotonic() if now is None else now
        ttl = self.config.idle_ttl_seconds
        for conversation_key in list(self.conversations):
            conv = self.conversations[conversation_key]
            if not conv.in_flight and now - conv.last_used > ttl:
                del self.conversations[conversation_key]
        for settings_key, settings in list(self.settings.items()):
            if now - settings.last_used > ttl:
                del self.settings[settings_key]
        for cooldown_key, expiry in list(self.cooldowns.items()):
            if expiry <= now:
                del self.cooldowns[cooldown_key]

    def _conversation(self, key: ConversationKey) -> Conversation:
        self._prune()
        conv = self.conversations.get(key)
        if conv is None:
            while len(self.conversations) >= self.config.max_sessions:
                evict = next((k for k, v in self.conversations.items() if not v.in_flight), None)
                if evict is None:
                    raise BotRequestError("Conversation capacity is busy; try again shortly.")
                del self.conversations[evict]
            conv = Conversation()
            self.conversations[key] = conv
        conv.last_used = time.monotonic()
        self.conversations.move_to_end(key)
        return conv

    @staticmethod
    def _trim(
        messages: list[dict[str, str]], max_messages: int, max_chars: int
    ) -> list[dict[str, str]]:
        # Keep only complete user/assistant pairs to avoid orphaned turns.
        if max_messages < 2:
            return []
        kept: list[dict[str, str]] = []
        chars = 0
        for i in range(len(messages) - 2, -1, -2):
            pair = messages[i : i + 2]
            if len(pair) != 2 or pair[0]["role"] != "user" or pair[1]["role"] != "assistant":
                continue
            size = sum(len(m["content"]) for m in pair)
            if kept and (len(kept) + 2 > max_messages or chars + size > max_chars):
                break
            if size > max_chars:
                continue
            kept[0:0] = pair
            chars += size
        return kept

    async def respond(
        self,
        scope: tuple[int, int, int],
        text: str,
        *,
        private: Optional[bool] = None,
        settings_snapshot: Optional[tuple[ProviderType, str, str]] = None,
    ) -> str:
        if len(text) > self.config.max_input_chars:
            raise BotRequestError(
                f"Message is too long (maximum {self.config.max_input_chars} characters)."
            )
        now = time.monotonic()
        cooldown_key = scope
        if self.cooldowns.get(cooldown_key, 0) > now:
            raise BotRequestError("Please wait a few seconds before sending another request.")
        if self._capacity.locked():
            raise BotRequestError("The bot is busy; please try again shortly.")
        settings = self.get_settings(scope)
        use_private = settings.private if private is None else private
        key = ConversationKey(scope[0], scope[1], scope[2], use_private)
        conv = self._conversation(key)
        if conv.in_flight:
            raise BotRequestError("A response is already being generated for this conversation.")
        if self._capacity.locked():
            raise BotRequestError("The bot is busy; please try again shortly.")
        await self._capacity.acquire()
        conv.in_flight = True
        self.cooldowns[cooldown_key] = now + self.config.cooldown_seconds
        try:
            # Freeze all mutable settings before the first provider await.
            provider_type, configured_model, persona = settings_snapshot or (
                settings.provider,
                settings.model,
                settings.persona,
            )
            model = configured_model if configured_model != "auto" else None
            persona_prompt = self._persona_prompt(persona, scope[2])
            messages = [
                {"role": "system", "content": self.config.system_prompt + "\n\n" + persona_prompt}
            ]
            messages.extend(
                self._trim(conv.messages, self.config.history_messages, self.config.history_chars)
            )
            messages.append({"role": "user", "content": text})
            provider = self.provider_manager.get_provider(provider_type)
            reply = await asyncio.wait_for(
                provider.chat_completion(
                    messages=messages,
                    model=model,
                    max_tokens=self.config.max_output_tokens,
                    request_timeout=self.config.request_timeout_seconds,
                ),
                timeout=self.config.request_timeout_seconds,
            )
            conv.messages.extend(
                [{"role": "user", "content": text}, {"role": "assistant", "content": reply}]
            )
            conv.messages = self._trim(
                conv.messages, self.config.history_messages, self.config.history_chars
            )
            return reply
        finally:
            conv.last_used = time.monotonic()
            conv.in_flight = False
            self._capacity.release()

    def reset(self, scope: tuple[int, int, int]) -> None:
        settings = self.get_settings(scope)
        for key, conv in self.conversations.items():
            if (key.guild_id, key.channel_id, key.user_id) == scope and conv.in_flight:
                raise BotRequestError("A response is in progress; retry reset after it finishes.")
        for key in [
            k for k in self.conversations if (k.guild_id, k.channel_id, k.user_id) == scope
        ]:
            del self.conversations[key]
        settings.persona = "standard"

    def _persona_prompt(self, persona: str, user_id: int) -> str:
        if persona not in personas.PERSONAS:
            raise BotRequestError("That persona is unavailable.")
        if personas.is_jailbreak_persona(persona) and user_id not in self.config.bot_admin_ids:
            raise BotRequestError("That persona is restricted to configured bot administrators.")
        return personas.PERSONAS[persona]

    async def generate_image(
        self,
        prompt: str,
        scope: tuple[int, int, int],
        settings_snapshot: Optional[tuple[ProviderType, str]] = None,
    ) -> str | bytes:
        if not self.config.enable_image_generation:
            raise BotRequestError("Image generation is disabled by the bot administrator.")
        if len(prompt) > self.config.max_input_chars:
            raise BotRequestError(
                f"Prompt is too long (maximum {self.config.max_input_chars} characters)."
            )
        settings = self.get_settings(scope)
        conv = self._conversation(ConversationKey(*scope, settings.private))
        if conv.in_flight:
            raise BotRequestError("A response is already being generated for this conversation.")
        if self._capacity.locked():
            raise BotRequestError("The bot is busy; please try again shortly.")
        now = time.monotonic()
        if self.cooldowns.get(scope, 0) > now:
            raise BotRequestError("Please wait a few seconds before sending another request.")
        await self._capacity.acquire()
        self.cooldowns[scope] = now + self.config.cooldown_seconds
        if conv.in_flight:
            self._capacity.release()
            raise BotRequestError("A response is already being generated for this conversation.")
        conv.in_flight = True
        try:
            provider_type, configured_model = settings_snapshot or (
                settings.provider,
                settings.model,
            )
            provider = self.provider_manager.get_provider(provider_type)
            if not provider.supports_image_generation():
                raise BotRequestError("Image generation is unavailable for this provider.")
            models = self.provider_manager.get_provider_models(provider_type)
            image_model = (
                configured_model
                if configured_model != "auto"
                and any(m.name == configured_model and m.supports_image_generation for m in models)
                else next((m.name for m in models if m.supports_image_generation), None)
            )
            return await asyncio.wait_for(
                provider.generate_image(prompt, model=image_model),
                timeout=self.config.request_timeout_seconds,
            )
        finally:
            conv.in_flight = False
            conv.last_used = time.monotonic()
            self._capacity.release()

    def _register_commands(self) -> None:
        @self.tree.error
        async def command_error(
            interaction: discord.Interaction, error: app_commands.AppCommandError
        ):
            original = (
                error.original if isinstance(error, app_commands.CommandInvokeError) else error
            )
            if isinstance(original, (BotRequestError, ProviderError)):
                message = str(original)
            else:
                message = "That command could not be completed. Please try again later."
            if interaction.response.is_done():
                await interaction.followup.send(
                    message, ephemeral=True, allowed_mentions=discord.AllowedMentions.none()
                )
            else:
                await interaction.response.send_message(
                    message, ephemeral=True, allowed_mentions=discord.AllowedMentions.none()
                )

        @self.tree.command(name="chat", description="Have a private or public chat with AI")
        async def chat(interaction: discord.Interaction, message: str):
            await self._chat_interaction(interaction, message)

        @self.tree.command(name="reset", description="Clear your conversation in this channel")
        async def reset(interaction: discord.Interaction):
            scope = self._scope(interaction)
            try:
                self.reset(scope)
                await interaction.response.send_message(
                    "Conversation cleared.",
                    ephemeral=True,
                    allowed_mentions=discord.AllowedMentions.none(),
                )
            except RuntimeError as exc:
                await interaction.response.send_message(str(exc), ephemeral=True)

        @self.tree.command(name="private", description="Toggle private replies for your chats")
        async def private(interaction: discord.Interaction):
            settings = self.get_settings(self._scope(interaction))
            settings.private = not settings.private
            await interaction.response.send_message(
                f"Private replies {'enabled' if settings.private else 'disabled'} for your chats in this channel. New sessions start private.",
                ephemeral=True,
            )

        @self.tree.command(name="provider", description="Choose your AI provider")
        async def provider(
            interaction: discord.Interaction,
            provider_name: str | None = None,
            model: str | None = None,
        ):
            scope = self._scope(interaction)
            if self._has_in_flight(scope):
                await interaction.response.send_message(
                    "A response is in progress; try again afterward.", ephemeral=True
                )
                return
            try:
                if provider_name is None:
                    names = ", ".join(
                        p.value for p in self.provider_manager.get_available_providers()
                    )
                    await interaction.response.send_message(
                        f"Available providers: {names}. Choose one using the provider option.",
                        ephemeral=True,
                    )
                    return
                provider_type = ProviderType(provider_name.lower())
                selected = self.provider_manager.get_provider(provider_type)
                model = model or "auto"
                if model != "auto" and model not in {
                    m.name
                    for m in selected.get_available_models()
                    if not m.supports_image_generation
                }:
                    raise ValueError("Unknown model")
                self.get_settings(scope).provider = provider_type
                self.get_settings(scope).model = model
                await interaction.response.send_message(
                    f"Provider set to {provider_type.value} ({model}).", ephemeral=True
                )
            except Exception:
                await interaction.response.send_message(
                    "That provider or model is unavailable.", ephemeral=True
                )

        @provider.autocomplete("provider_name")
        async def provider_autocomplete(interaction: discord.Interaction, current: str):
            values = [
                p.value
                for p in self.provider_manager.get_available_providers()
                if current.lower() in p.value
            ]
            return [app_commands.Choice(name=value, value=value) for value in values[:25]]

        @provider.autocomplete("model")
        async def model_autocomplete(interaction: discord.Interaction, current: str):
            scope = self._scope(interaction)
            settings = self.get_settings(scope)
            provider_name = getattr(interaction.namespace, "provider_name", None)
            try:
                kind = ProviderType(provider_name or settings.provider.value)
                models = self.provider_manager.get_provider_models(kind)
            except ValueError:
                models = []
            values = ["auto"] + [
                m.name
                for m in models
                if not m.supports_image_generation and current.lower() in m.name.lower()
            ]
            return [app_commands.Choice(name=value[:100], value=value) for value in values[:25]]

        @self.tree.command(name="switchpersona", description="Switch your assistant persona")
        async def switchpersona(interaction: discord.Interaction, persona: str):
            scope = self._scope(interaction)
            try:
                self._persona_prompt(persona, scope[2])
                if self._has_in_flight(scope):
                    raise BotRequestError("A response is in progress; try again afterward.")
                self.get_settings(scope).persona = persona
                await interaction.response.send_message(
                    f"Persona set to {persona}.", ephemeral=True
                )
            except (PermissionError, ValueError, RuntimeError):
                await interaction.response.send_message(
                    "That persona is unavailable or your conversation is busy.", ephemeral=True
                )

        @self.tree.command(
            name="replyall", description="Toggle replies to messages in this channel"
        )
        async def replyall(interaction: discord.Interaction):
            scope = self._scope(interaction)
            if not self.is_admin(interaction.user.id, interaction):
                await interaction.response.send_message(
                    "Manage Channels permission or bot-admin access is required.", ephemeral=True
                )
                return
            if not self.config.enable_message_content:
                await interaction.response.send_message(
                    "Message content intent is disabled in bot configuration.", ephemeral=True
                )
                return
            if scope[1] not in self.config.replyall_channel_ids:
                await interaction.response.send_message(
                    "This channel is not configured for reply-all mode.", ephemeral=True
                )
                return
            if scope[1] in self.replyall_enabled:
                self.replyall_enabled.remove(scope[1])
                enabled = False
            else:
                self.replyall_enabled.add(scope[1])
                enabled = True
            await interaction.response.send_message(
                f"Reply-all {'enabled' if enabled else 'disabled'} in this channel.", ephemeral=True
            )

        @self.tree.command(name="draw", description="Generate an image from a prompt")
        async def draw(interaction: discord.Interaction, prompt: str):
            if not self.config.enable_image_generation:
                await interaction.response.send_message(
                    "Image generation is disabled by the bot administrator.", ephemeral=True
                )
                return
            prompt = prompt.replace("\x00", "").strip()
            if not prompt:
                await interaction.response.send_message(
                    "Please provide an image prompt.", ephemeral=True
                )
                return
            scope = self._scope(interaction)
            try:
                settings = self.get_settings(scope)
            except BotRequestError as exc:
                await interaction.response.send_message(str(exc), ephemeral=True)
                return
            visibility = settings.private
            settings_snapshot = (settings.provider, settings.model)
            await interaction.response.defer(ephemeral=visibility)
            if not self.allowed(scope):
                await interaction.followup.send(
                    "This bot is not enabled in this server or channel.", ephemeral=visibility
                )
                return
            try:
                image = await self.generate_image(prompt, scope, settings_snapshot)
                embed = discord.Embed(title="Generated image", description=prompt[:1000])
                if isinstance(image, str):
                    embed.set_image(url=image)
                    await interaction.followup.send(
                        embed=embed,
                        ephemeral=visibility,
                        allowed_mentions=discord.AllowedMentions.none(),
                    )
                else:
                    await interaction.followup.send(
                        file=discord.File(io.BytesIO(image), filename="generated.png"),
                        ephemeral=visibility,
                        allowed_mentions=discord.AllowedMentions.none(),
                    )
            except ProviderError as exc:
                await interaction.followup.send(
                    str(exc), ephemeral=visibility, allowed_mentions=discord.AllowedMentions.none()
                )
            except BotRequestError as exc:
                await interaction.followup.send(
                    str(exc), ephemeral=visibility, allowed_mentions=discord.AllowedMentions.none()
                )
            except Exception:
                await interaction.followup.send(
                    "Image generation failed. Please check provider configuration and try again.",
                    ephemeral=visibility,
                    allowed_mentions=discord.AllowedMentions.none(),
                )

        @self.tree.command(name="status", description="Show your current bot settings")
        async def status(interaction: discord.Interaction):
            s = self.get_settings(self._scope(interaction))
            provider = self.provider_manager.get_provider(s.provider)
            model = (
                s.model
                if s.model != "auto"
                else getattr(provider, "default_model", "provider default")
            )
            await interaction.response.send_message(
                f"Provider: {s.provider.value}\nModel: {model}\nPersona: {s.persona}\nPrivate: {'on' if s.private else 'off'}",
                ephemeral=True,
            )

        @self.tree.command(name="help", description="Show bot commands")
        async def help_command(interaction: discord.Interaction):
            await interaction.response.send_message(
                "Use /chat to talk, /reset to clear your channel conversation, /private to toggle private replies, /provider to choose a provider, /switchpersona to change persona, /draw for images, and /status to view your settings. Reply-all is administrator controlled.",
                ephemeral=True,
            )

        self._commands = {c.name: c for c in self.tree.get_commands()}

    def _has_in_flight(self, scope: tuple[int, int, int]) -> bool:
        return any(
            c.in_flight and (k.guild_id, k.channel_id, k.user_id) == scope
            for k, c in self.conversations.items()
        )

    async def _chat_interaction(self, interaction: discord.Interaction, message: str) -> None:
        scope = self._scope(interaction)
        if not self.allowed(scope):
            await interaction.response.send_message(
                "This bot is not enabled in this server or channel.", ephemeral=True
            )
            return
        message = message.replace("\x00", "").strip()
        if not message:
            await interaction.response.send_message("Please provide a message.", ephemeral=True)
            return
        if len(message) > self.config.max_input_chars:
            await interaction.response.send_message(
                f"Message is too long (maximum {self.config.max_input_chars} characters).",
                ephemeral=True,
            )
            return
        try:
            settings = self.get_settings(scope)
        except BotRequestError as exc:
            await interaction.response.send_message(
                str(exc), ephemeral=True, allowed_mentions=discord.AllowedMentions.none()
            )
            return
        private = settings.private
        settings_snapshot = (settings.provider, settings.model, settings.persona)
        await interaction.response.defer(ephemeral=private)
        try:
            reply = await self.respond(
                scope, message, private=private, settings_snapshot=settings_snapshot
            )
            from utils.message_utils import send_split_message

            await send_split_message(reply, interaction, ephemeral=private)
        except BotRequestError as exc:
            await interaction.followup.send(
                str(exc), ephemeral=private, allowed_mentions=discord.AllowedMentions.none()
            )
        except ProviderError as exc:
            await interaction.followup.send(
                str(exc), ephemeral=private, allowed_mentions=discord.AllowedMentions.none()
            )
        except Exception:
            await interaction.followup.send(
                "I couldn't complete that request. Please try again later.",
                ephemeral=private,
                allowed_mentions=discord.AllowedMentions.none(),
            )

    async def on_ready(self) -> None:
        if self.user:
            await self.change_presence(
                activity=discord.Activity(type=discord.ActivityType.listening, name="/chat | /help")
            )

    async def on_message(self, message: discord.Message) -> None:
        if (
            message.author.bot
            or message.webhook_id
            or message.channel.id not in self.replyall_enabled
        ):
            return
        if not self.config.enable_message_content:
            return
        if message.channel.id not in self.config.replyall_channel_ids:
            return
        scope = self._scope(message)
        if not self.allowed(scope):
            return
        content = (message.content or "").strip()
        if not content or len(content) > self.config.max_input_chars:
            return
        # Public-message context is always its own non-private conversation key.
        try:
            settings = self.get_settings(scope)
            settings_snapshot = (settings.provider, settings.model, settings.persona)
            async with message.channel.typing():
                reply = await self.respond(
                    scope, content, private=False, settings_snapshot=settings_snapshot
                )
            from utils.message_utils import send_split_message

            await send_split_message(reply, message, ephemeral=False)
        except ProviderError as exc:
            await message.channel.send(str(exc), allowed_mentions=discord.AllowedMentions.none())
        except BotRequestError as exc:
            await message.channel.send(str(exc), allowed_mentions=discord.AllowedMentions.none())
        except Exception:
            await message.channel.send(
                "I couldn't complete that request. Please try again later.",
                allowed_mentions=discord.AllowedMentions.none(),
            )
